### ISSUE TITLE
Umwandlung des Trademark-Symbols von csv nach json

### ISSUE THREAD

**Issue by kkotenko** [lenaschimmel/schnelltestrechner#11]
Manche Herstellernamen enthalten in der json-Datei nicht-druckbare Zeichen (Hex-Code 99), siehe zB. Panbio. 
Auf dem Desktop werden diese einfach nicht angezeigt, auf dem Handy (Android, Chrome) erscheint die Box für nicht-druckbares Zeichen. 

Soweit ich sehe, handelt es sich bei allen Instanzen davon um das Trademark-Symbol (Hex-Code 2122). https://github.com/lenaschimmel/schnelltestrechner/blob/main/data/antigentests.csv#L2

**Comment by lenaschimmel** [comment]
Spannend. Habe mich schon gefragt, welche Kodierung ich zum Parsen nehmen muss, damit 0x99 zu Trademark wird. Laut [Stackoverflow](https://stackoverflow.com/questions/28446264/how-to-show-or-convert-non-standard-u0099-for-trademark-tm-character) dürfte das nicht vorkommen, kommt aber wohl dennoch manchmal bei Daten aus China vor.

Vermutlich/hoffentlich kann ich das in JS einfach einfach ersetzen, auch wenn ich da mit einem nicht-zugewiesenen Unicode-Codepoint arbeite.

**Comment by lenaschimmel** [comment]
Gerade entdeckt: Bei manchen Tests wird zur Angabe von Wertebereichen, wie etwa `88,8 - 95,5` für den Stich nicht etwa `0x2D` verwendet, sondern `0x96`. Das Byte ist in IEC_8859-1 nicht belegt, und das Parsen dieser Wertebereiche schlägt fehl.

**Comment by lenaschimmel** [comment]
Beides erledigt (TM und Minuszeichen).
