### ISSUE TITLE
[feature] Alphabetische Sortierung des Test-Dropdowns

### ISSUE THREAD

**Issue by kkotenko** [lenaschimmel/schnelltestrechner#12]
Es wäre super, wenn die Liste der Tests bei der Ausgabe im Browser alphabetisch sortiert wäre.

**Comment by lenaschimmel** [comment]
Ja, diese Liste ist die größte UI-Baustelle an dem ganzen Projekt und muss komplett neu gestaltet werden (hatte eben noch eine Unterhaltung mit jemand anderem darüber…). Vermutlich hätte ich das Projekt noch gar nicht veröffentlicht, wenn ich dran gedacht hätte, _wie_ schlecht diese Liste gerade ist.

Ggf. werde ich die aber dennoch gleich noch eben sortieren, bevor ich sie neu baue (#15), ist ja nur eine Zeile Code.

**Comment by lenaschimmel** [comment]
Ging noch einfacher als erwartet.
