### ISSUE TITLE
Swipe-Navigation-Verhalten auf Android/Chrome

### ISSUE THREAD

**Issue by kkotenko** [lenaschimmel/schnelltestrechner#19]
Precondition: 
1) Ich befinde mich auf der Webseite im Rechner-Tab.
2) Browser: Google Chrome 89 auf Android, Viewport-Breite 360px

Behavior:
1) Ich swipe am rechten Rand von rechts nach links. Das führt dazu, dass ich jetzt im Info-Tab bin.
2) Ich swipe am linken Rand von links nach rechts. Das kann sehr schnell dazu führen, dass mein Browser die history.back()-Funktion durchführt, wenn ich nämlich zu weit in die Mitte swipe.
3) Analog kann es in Schritt 1 passieren, dass mein Browser die history.forward()-Funktion durchführt, wenn es einen "zukünftigen" Eintrag in der history gibt.

Ist in erster Linie nervig in Verbindung mit Issue #18 - von mir aus finde ich, man könnte auf die Navigation via Swipe hier verzichten, ich habe sie nicht vermisst, bis ich aus Versehen drauf gestoßen bin.

**Comment by lenaschimmel** [comment]
Spannend, mir war gar nicht bewusst, dass es da überhaupt einen Swipe-Navigation gibt. Erscheint mir auch in dem Kontext nicht wichtig, also werde ich die wohl einfach beim nächsten Update deaktivieren.

**Comment by lenaschimmel** [comment]
Swipe-Navigation deaktiviert.
