### ISSUE TITLE
Viele Symptome senken das Risiko

### ISSUE THREAD

**Issue by xpac1985** [lenaschimmel/schnelltestrechner#21]
Hey,

danke für deine (eure?) Arbeit!
Mir ist aufgefallen, dass das Risiko sinkt, wenn man besonders viele Symptome auswählt - hier zwei Beispiele:

![grafik](https://user-images.githubusercontent.com/6882771/112619049-2032c900-8e27-11eb-8233-6bbc17d848eb.png)

![grafik](https://user-images.githubusercontent.com/6882771/112619075-26c14080-8e27-11eb-8aaf-85adb6792b51.png)

Ich vermute das ist nicht beabsichtigt?

**Comment by lenaschimmel** [comment]
> Mir ist aufgefallen, dass das Risiko sinkt, wenn man besonders viele Symptome auswählt

Hallo und danke für die Meldung!

## Kurzfassung

**Diese Sache ist etwas unintuitiv, aber beabsichtigt und (hoffentlich!) korrekt.**

## Langfassung

Die Auswirkung der Symptome wird nach dem Paper [A Symptom-Based Rule for Diagnosis of COVID-19](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7584484/) berechnet. Darin wurde bei 240 symptomatischen Patient_innen ca. 25 verschiedene Symptome und diverse Symptom-Kombinationen betrachtet, und wie sehr diese damit korrelieren, dass diejenigen im PCR-Test Covid-Positiv oder -negativ waren.

Daraus wurden die Kombinationen ermittelt, welche die größte Aussagekraft haben:

![Bildschirmfoto 2021-03-26 um 13 18 06](https://user-images.githubusercontent.com/1325019/112630834-73604800-8e36-11eb-8ac9-7c7ad92e44fb.png)

Zu Beachten ist in der Tabelle einerseits, dass manche mit _'und'_ und andere mit _'oder'_ verknüpft sind, sowie die Spalte _'β-Coefficient'_. "Wheeze or chest tightness" hat hier einen negativen Koeffizienten. Weiter unten im Paper wurde das ganze noch zu einer handlichen Regel verarbeitet, die man sich ggf. auch einprägen und ganz ohne Computer auswerten kann. Dabei werden Punkte für die Symptome vergeben und dann zusammen gezählt. Die Punkte sind die auf ganze Zahlen gerundeten β-Koeffizienten:

 * loss of smell or taste (2 points)
 * fever and cough (1 point)
 * and wheezing or chest tightness (− 1 point).

![Bildschirmfoto 2021-03-26 um 13 18 18](https://user-images.githubusercontent.com/1325019/112630862-7a875600-8e36-11eb-8919-697ea8070db2.png)

Das Vorhandensein von Keuchen oder Engegefühl spricht demnach so sehr für eine _andere_ Atemwegserkrankung, dass die Wahrscheinlichkeit für Covid-19 sinkt.

Soweit der Teil bei dem ich ziemlich sicher bin. 

## Basis-Faktor

Und jetzt das, wo ich selbst noch nicht sicher bin, ob das insgesamt so korrekt ist:

Es ist nun so implementiert, dass Keuchen oder Engegefühl die Wahrscheinlichkeit für Covid-19 _im Vergleich zu einer Symptomlosen Person_ nicht wirklich senkt, sondern nur weniger stark erhöht als eine Symptomkombination ohne Keuchen und Engegefühl.

Dazu erhöht das Vorkommen _irgendwelcher_ Symptome, die _Likelihood_ erstmal um den Faktor 18.8, und die spezifischen Symptome können das dann noch etwas weiter steigern oder senken (durch Multiplikation mit der _likelyhood ratio_ aus Tabelle 3), je nach Ergebnis der oben genannten Punkteregel.

Ich finde es einleuchtend, dass es einen solchen Basisfaktor geben muss, aber habe auch an diversen Stellen kommuniziert, dass dieser konkrete Faktor nicht besonders gut belegt ist, z.B. in Issue #9 (Symptome erhöhen die VTW um einen schlecht bestimmten Faktor).

## Ich / Wir?

> danke für deine (eure?) Arbeit!

Ich wechsle da selbst oft zwischen _'ich'_ und _'wir'_. Noch ist ein großteil der Arbeit von mir selbst, aber zum Glück tragen immer mehr Menschen einen Anteil dazu bei, so dass daraus langsam ein wir wird.

**Comment by lenaschimmel** [comment]
PS: Das ganze wird etwas durchschaubarer, wenn man oben rechts die "Erweiterte Ansicht" aktiviert:

![Bildschirmfoto 2021-03-26 um 13 46 23](https://user-images.githubusercontent.com/1325019/112633500-b5d75400-8e39-11eb-91a2-0c7d77d70789.png)

**Comment by xpac1985** [comment]
Hey,
danke für die ausführliche Antwort - ich hatte ein bisschen vermutet, dass sowas zum tragen kommt, aber war mir nicht sicher.
Möglicherweise macht es Sinn eine kleine Info einzublenden, wenn man eins von den beiden "Minus"-Symptomen auswählt? Ich kann mir vorstellen dass da häufiger mal jemand verwundert vorsitzt :)

**Comment by lenaschimmel** [comment]
Guter Idee, ist erledigt!

![Bildschirmfoto 2021-03-26 um 14 47 16](https://user-images.githubusercontent.com/1325019/112641218-73fedb80-8e42-11eb-9a4d-5dd405417ba1.png)
