### ISSUE TITLE
Auswahlliste Landkreis: Uneindeutigkeiten

### ISSUE THREAD

**Issue by kevpr** [lenaschimmel/schnelltestrechner#22]
In der Auswahlliste für Landkreise ist Osnabrück zweimal vorhanden, und nicht voneinander unterscheidbar. Gemeint sind sicherlich Landkreis bzw. kreisfreie Stadt, aber in der Liste lässt sich keine geeignete Auswahl treffen. Ich schlage vor, sie jeweils mit Zusätzen zu versehen, etwa "(Landkreis)" bzw. "(Stadt)". Ähnliches gilt auch für Oldenburg.

**Comment by kkotenko** [comment]
Duplikate in der Liste sind
```
Ansbach
Aschaffenburg
Augsburg
Bamberg
Bayreuth
Coburg
Fürth
Heilbronn
Hof
Kaiserslautern
Karlsruhe
Kassel
Landshut
Leipzig
München
Osnabrück
Passau
Regensburg
Rosenheim
Rostock
Schweinfurt
Würzburg
```

Oldenburg ist einmal als "Oldenburg" und einmal als "Oldbenburg (Oldb)" vorhanden.

**Comment by lenaschimmel** [comment]
Ja, das ist ein Problem.

Die Anzeigenamen kommen aus [dieser API](https://api.corona-zahlen.org/docs/endpoints/districts.html#districts-2), und ich verwende im Moment den `name` zur Anzeige, der offenbar nicht eindeutig ist.

    "03404": {
        "ags": "03404",
        "name": "Osnabrück",
        "county": "SK Osnabrück",
        "state": "Niedersachsen",
        "population": 165251,
        "cases": 5559,
        "deaths": 88,
        "casesPerWeek": 284,
        "deathsPerWeek": 0,
        "stateAbbreviation": "NI",
        "recovered": 4982,
        "weekIncidence": 171.859776945374,
        "casesPer100k": 3363.9735916877958,
        "delta": {
            "cases": 73,
            "deaths": 0,
            "recovered": 26
        }
    },
    "03459": {
        "ags": "03459",
        "name": "Osnabrück",
        "county": "LK Osnabrück",
        "state": "Niedersachsen",
        "population": 358080,
        "cases": 12322,
        "deaths": 268,
        "casesPerWeek": 411,
        "deathsPerWeek": 1,
        "stateAbbreviation": "NI",
        "recovered": 11405,
        "weekIncidence": 114.77882037533513,
        "casesPer100k": 3441.130473637176,
        "delta": {
            "cases": 130,
            "deaths": 0,
            "recovered": 24
        }
    }

Alternativen: 

1. Könnte stattdessen auch das Attribut `county` benutzen, das ist eindeutig, da dann in der Regel "SK" oder "LK" davor steht. (Ausnahme: Aachen wird dann von "Städteregion Aachen" zu StadtRegion Aachen"). Das wäre trivial umzusetzen, aber macht für die User die Suche in der Liste etwas weniger intuitiv.
2. Von den `county`-Werten könnte ein `LK` oder `SK` vorne abgeschnitten werden, und hinten angehängt, z.B. `Osnabrück (LK)`
3. Wie 2., aber nur dort `(LK)` oder `(SK)` anhängen, wo es sonst nicht eindeutig wäre
4. Die Landkreisauswahl generell überarbeiten, wie @kkotenko eben in #23 vorgeschlagen hat.

**Comment by lenaschimmel** [comment]
PS: Werde wohl vorerst Variante 2 & 4 kombinieren, in einem späteren Schritt dann 3 & 4.

**Comment by lenaschimmel** [comment]
Doch alles etwas komplexer… die konkrete API `` enhtält zwar auch die Daten der Vorwoche (wird für die Extrapolation der Prävalenz gebraucht) aber nicht die vollständigen Bezeichnungen:

     "09777": {
        "ags": "09777",
        "name": "Ostallgäu",
        "history": [
            {
                "weekIncidence": 164.32689719652646,
                "date": "2021-03-19T00:00:00.000Z"
            },
            <...>
            {
                "weekIncidence": 265.61459676162684,
                "date": "2021-03-26T00:00:00.000Z"
            }
        ]
    },

Muss das also noch mit eine weiteren Datenquelle verbinden :/

**Comment by lenaschimmel** [comment]
Fix ist online.

<img width="1229" alt="Bildschirmfoto 2021-03-27 um 17 28 51" src="https://user-images.githubusercontent.com/1325019/112727242-eb576c80-8f21-11eb-8dba-59fb9195c156.png">
