### ISSUE TITLE
[interface] Liste der Landkreise filterbar machen

### ISSUE THREAD

**Issue by kkotenko** [lenaschimmel/schnelltestrechner#23]
Die Liste der Landkreise sollte per Tippen filterbar sein, ähnlich wie die Liste der Tests.

**Comment by lenaschimmel** [comment]
Sehr guter Punkt. Wollte das schon eher machen, hatte aber Probleme damit, das [`v-combobox`](https://vuetifyjs.com/en/components/combobox/) korrekt zu konfigurieren.

Habe eben realsiert, dass ich stattdessen ein [`v-autocomplete`](https://vuetifyjs.com/en/components/autocompletes/) nehmen sollte, damit wird es einfacher sein.

**Comment by lenaschimmel** [comment]
Fix ist online.

<img width="1229" alt="Bildschirmfoto 2021-03-27 um 17 28 51" src="https://user-images.githubusercontent.com/1325019/112727251-ff02d300-8f21-11eb-95d5-746d1a421f15.png">
